# Generated by Django 5.2.9 on 2026-02-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("General Medicine", "General Medicine"),
                            ("Cardiology", "Cardiology"),
                            ("Dermatology", "Dermatology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Neurology", "Neurology"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("ENT", "ENT"),
                            ("Dentistry", "Dentistry"),
                            ("Psychiatry", "Psychiatry"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(help_text="Years of experience"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
