# Generated by Django 5.2.9 on 2026-02-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "med_type",
                    models.CharField(
                        choices=[
                            ("Tablet", "Tablet"),
                            ("Capsule", "Capsule"),
                            ("Syrup", "Syrup"),
                            ("Injection", "Injection"),
                            ("Ointment", "Ointment"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(help_text="e.g., 500mg, 10ml", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("General Checkup", "General Checkup"),
                            ("Dental Care", "Dental Care"),
                            ("Cardiology Consultation", "Cardiology Consultation"),
                            ("Eye Examination", "Eye Examination"),
                            ("Skin Treatment", "Skin Treatment"),
                            ("Orthopedic Consultation", "Orthopedic Consultation"),
                            ("Pediatric Care", "Pediatric Care"),
                            ("Neurological Assessment", "Neurological Assessment"),
                            ("ENT Consultation", "ENT Consultation"),
                            ("Mental Health Counseling", "Mental Health Counseling"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "suggested_medicines",
                    models.ManyToManyField(
                        blank=True, related_name="appointments", to="medicines.medicine"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
    ]
