# Generated by Django 5.2.9 on 2026-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
