# Generated by Django 5.2.9 on 2026-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Dental", "Dental"),
                    ("Cardiology", "Cardiology"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Dermatology", "Dermatology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Pediatrics", "Pediatrics"),
                    ("Neurology", "Neurology"),
                    ("ENT", "ENT"),
                    ("Psychiatry", "Psychiatry"),
                ],
                default="General",
                help_text="Medical category this medicine belongs to",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description or usage instructions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="med_type",
            field=models.CharField(
                choices=[
                    ("Tablet", "Tablet"),
                    ("Capsule", "Capsule"),
                    ("Syrup", "Syrup"),
                    ("Injection", "Injection"),
                    ("Ointment", "Ointment"),
                    ("Drops", "Drops"),
                    ("Inhaler", "Inhaler"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
