# Generated by Django 5.2.9 on 2026-02-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0003_alter_medicine_options_medicine_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Dental", "Dental"),
                    ("Cardiology", "Cardiology"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Dermatology", "Dermatology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Pediatrics", "Pediatrics"),
                    ("Neurology", "Neurology"),
                    ("ENT", "ENT"),
                    ("Psychiatry", "Psychiatry"),
                ],
                default="General",
                help_text="Medical category",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=models.TextField(
                blank=True, help_text="Brief description or usage", null=True
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Once daily", "Once daily"),
                            ("Twice daily", "Twice daily (Morning & Night)"),
                            ("Three times daily", "Three times daily"),
                            ("Four times daily", "Every 6 hours"),
                            ("Every 8 hours", "Every 8 hours"),
                            ("Before meals", "Before meals"),
                            ("After meals", "After meals"),
                            ("At bedtime", "At bedtime only"),
                            ("As needed", "As needed (SOS)"),
                            ("Once weekly", "Once weekly"),
                        ],
                        default="Twice daily",
                        max_length=30,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("3 days", "3 days"),
                            ("5 days", "5 days"),
                            ("7 days", "1 week"),
                            ("10 days", "10 days"),
                            ("14 days", "2 weeks"),
                            ("21 days", "3 weeks"),
                            ("30 days", "1 month"),
                            ("60 days", "2 months"),
                            ("90 days", "3 months"),
                            ("Ongoing", "Ongoing"),
                        ],
                        default="5 days",
                        max_length=30,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Take with water",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("prescribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medicines.appointment",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medicines.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["medicine__name"],
                "unique_together": {("appointment", "medicine")},
            },
        ),
    ]
